### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by karan** [nuprl/10PL#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by LeifAndersen** [comment]
While I am sympathetic to your cause, it is a bit silly to add a license to a repo that is just a list of 10 citations.

Also, as bennn said, this repo doesn't have any code in it. And the MIT and GPL licenses aren't intended for non-code works of art. A better license for that would be something like CC-BY or CC-BY-SA.
